-- tests/bufstate/state_spec.lua
-- Unit tests for bufstate.state — pure data module.

local state = require("bufstate.state")

describe("bufstate.state", function()
	before_each(function()
		state.reset()
	end)

	describe("add / has", function()
		it("associates a buffer with a tab", function()
			state.add(1, 42)
			assert.is_true(state.has(1, 42))
		end)

		it("allows a buffer in multiple tabs", function()
			state.add(1, 42)
			state.add(2, 42)
			assert.is_true(state.has(1, 42))
			assert.is_true(state.has(2, 42))
		end)

		it("returns false for unknown tab", function()
			assert.is_false(state.has(999, 42))
		end)

		it("returns false for unknown buffer in known tab", function()
			state.add(1, 42)
			assert.is_false(state.has(1, 99))
		end)
	end)

	describe("remove", function()
		it("removes buffer from all tabs", function()
			state.add(1, 42)
			state.add(2, 42)
			state.remove(42)
			assert.is_false(state.has(1, 42))
			assert.is_false(state.has(2, 42))
		end)

		it("does not affect other buffers", function()
			state.add(1, 42)
			state.add(1, 43)
			state.remove(42)
			assert.is_true(state.has(1, 43))
		end)

		it("is a no-op for unknown buffer", function()
			state.add(1, 42)
			state.remove(99)
			assert.is_true(state.has(1, 42))
		end)
	end)

	describe("get", function()
		it("returns all buffers for a tab", function()
			state.add(1, 42)
			state.add(1, 43)
			local bufs = state.get(1)
			table.sort(bufs)
			assert.are.same({ 42, 43 }, bufs)
		end)

		it("returns empty table for unknown tab", function()
			local bufs = state.get(999)
			assert.are.same({}, bufs)
		end)
	end)

	describe("purge_tab", function()
		it("removes a dead tab entry", function()
			state.add(1, 42)
			state.purge_tab(1)
			assert.is_false(state.has(1, 42))
		end)
	end)

	describe("reset", function()
		it("wipes all state", function()
			state.add(1, 42)
			state.add(2, 43)
			state.reset()
			assert.is_false(state.has(1, 42))
			assert.is_false(state.has(2, 43))
		end)
	end)
end)
